//绑定“现在报名”这个按钮的函数
//用户登陆了，则直接发送请求给报名接口（不需要携带参数）；未登陆则弹出登陆框
(function(){
    $('div.footer').on('click','.registration-a',function(){
        this.userInfo = store.get('userInfo');
        //this.userInfo = true;
        if(this.userInfo){
            //如果用户已经登陆，则直接发送请求给报名接口
            $.ajax({
                //url:AmApi.register,
                url:'/json/31.json',//随便写的接口
                type:'GET',
                error:function(){
                    alert('报名请求失败');
                },
                success:function(res){
                    if(res.state==true){
                        alert('报名成功');
                    }else{
                        alert(res.msg);
                    }
                }
            });
        }
        else{
            //如果用户没有登陆，则弹出登陆窗口
            userDialog.showLoginDialog();
        }
    });
})();